apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mongodb.fullname" . }}-secret
  labels:
    app: mongodb-backup-s3-secret
    app.kubernetes.io/name: mongodb-backup-s3-secret
type: Opaque
stringData:
  MONGODB_PASSWORD: {{ .Values.mongodb.password | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKey | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey | quote }}
